[project]
org-name = "hackbros"
version = "0.0.1"
authors = ["divyansh"]
repository = "https://github.com/sibbsnb/module-slack"
keywords = ["slack", "chatbot"]
license = ["Apache-2.0"]

[dependencies]
