[project]
org-name = "wso2"
version = "0.0.1"
authors = ["apachecon_hackbros"]
repository = "https://github.com/sibbsnb/module-slack"
keywords = ["slack", "slackbot"]
license = ["Apache-2.0"]

[dependencies]
